### ISSUE TITLE
実行すると[ERROR] Can't find a diff executable in PATHが出る

### ISSUE THREAD

**Issue by yamada153** [ridgepole/ridgepole#384]
rails 7.0.2
ruby 3.0
ridgepole 1.0.4
diffy 3.4.0
postgresql
windows11

こんにちわ。約2年前くらいからridgepoleを使用させていただいております。ただ最近
```
ridgepole --config config/database.yml --env development --file db/Schemafile --apply
```
を実行すると

```
[ERROR] Can't find a diff executable in PATH C:\Program Files\ImageMagick-7.0.10-Q16-HDRI;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files (x86)\Yarn\bin\;C:\Ruby27-x64\Git\cmd;C:\Program Files (x86)\Vim\vim82;C:\Program Files\Redis\;C:\Program Files\Git\cmd;C:\Program Files\nodejs\;C:\Program Files\PostgreSQL\14\bin;C:\Ruby31-x64\bin;C:\Ruby30-x64\bin;C:\Users\amezi\AppData\Local\Programs\Microsoft VS Code\bin;C:\Program Files\heroku\bin;C:\Users\amezi\AppData\Local\Microsoft\WindowsApps;C:\Users\amezi\AppData\Roaming\npm;C:\Program Files\PostgreSQL\14\bin
        C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/diffy-3.4.0/lib/diffy/diff.rb:169:in `diff_bin'
```
このようなエラーが発生するようになりました。
rails db:createをしてから一回目のコマンドは成功するのですが、カラムの追加や変更をしようと2回目にコマンドを実行すると上記のエラーが出る感じです。

ネットで見る限り同じ症状の人がいないのでもしかしたら僕の環境のせいかもしれませんが確認していただけると幸いです。

```
create_table :posts do |t|
  t.string :title
end

create_table :users do |t|
  t.string :name
end
```

```
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  password: xxx
  host: localhost
  username: postgres

development:
  <<: *default
  database: sample_api_development
```
