### ISSUE TITLE
Can not load ERB on database.yml?

### ISSUE THREAD

**Issue by Yucky39** [ridgepole/ridgepole#422]
# Description
Write an erb in database.yml that applies credentials and do ridgepole -apply, 
I get `[ERROR] uninitialized constant Rails` comes up and Rails will not be executed.

- database.yml
```yaml
    20  development:
    21    <<: *default
    22    database: app_development
    23    username: <%= Rails.application.credentials.development[:username] %>
    24    password: <%= Rails.application.credentials.development[:password] %>
    25    host: <%= Rails.application.credentials.development[:host] %>
```

- Rails credentials:show
```
development:
  username: root
  password: password
  host: db

# Used as the base secret for all MessageVerifiers in Rails, including the one protecting cookies.
secret_key_base: hogehogehogehoge

```

- Full text of runtime error
```
[ERROR] uninitialized constant Rails
        (erb):23:in `<main>'
rails aborted!
```

But, I don't write credentials and put the value in plain text,
Ridgepole will of course succeed!

- database.yml
```yaml
development:: *default
  <<: *default
  database: app_development
  username: root
  password: password
  host: db
```

- execute ridgepole --apply, full text runtime 
```
** Invoke ridgepole:apply (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute ridgepole:apply
ridgepole -E development -c config/database.yml --apply -f db/schemas/Schemafile
Apply `db/schemas/Schemafile` -- create_table("users")
-- create_table("users", {:charset=>"utf8mb4", :collation=>"utf8mb4_0900_ai_ci", :options=>"ENGINE=InnoDB ROW_FORMAT=DYNAMIC"})
   -> 0.0491s
-- add_index("users", ["name"], {:name=>"index_authors_on_name"})
   -> 0.0581s
rake db:schema:dump
```

Is it possible to apply Ridgepole in database.yml with credentials written in erb? 🤔 

Answer in Japanese is OK👌 

My environment versions.
- Ridgepole: 1.2.0
- Ruby: 3.1.4
- Rails:  7.0.5
- MySQL: 8.0.33

# Schemafile

- Schemafile
```
require 'users.schema.rb'
```

- users.schema.rb
```ruby
create_table :users, force: :cascade, charset: 'utf8mb4', collation: 'utf8mb4_0900_ai_ci', options: 'ENGINE=InnoDB ROW_FORMAT=DYNAMIC' do |t|
  t.string  :name, null: false, default: ''
  t.integer :age,  null: false, default: 20

  t.index :name, name: 'index_authors_on_name'
end
```
